### ISSUE TITLE
UUID issue

### ISSUE THREAD

**Issue by romanoff** [NZKoz/cassandra_object#10]
Seems like cassandra gem has no `Cassandra::UUID` class. I replaced it with `SimpleUUID::UUID` and I could require cassandra and cassandra_object without errors. But then when I created class inherited from `CassandraObject::Base` and tried to create new user instance with some parameters: `User.new(:first_name => "name")`, I got error:

```
irb(main):020:0> User.new(:first_name => "name")
NoMethodError: undefined method 'encode' for nil:NilClass
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:14:in `check_value!'
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:62:in `write_attribute'
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/dirty.rb:23:in `write_attribute'
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:89:in `attribute='
from /usr/local/lib/ruby/gems/1.9.1/gems/activemodel-3.0.0.beta3/lib/active_model/attribute_methods.rb:273:in `first_name='
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:74:in `block in attributes='
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:73:in `each'
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/attributes.rb:73:in `attributes='
from /home/ras/Programming/NoSQL/cassandra_object/lib/cassandra_object/base.rb:98:in `initialize'
from (irb):20:in `new'
from (irb):20
from /usr/local/bin/irb:12:in '<main>'
```

although `:first_name` attribute was set in User class.
I was using ruby 1.9.1, rails3 beta3, cassandra 0.8.2 gem, cassandra 0.6.

**Comment by NZKoz** [comment]
SimpleUUID now provides the UUID impl

closed by 64df85ec7e0d44a2b0cba832f33e4c9fc40a2635
